# Generated by Django 5.2.15 on 2026-06-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., BCG, HepB, DTaP-IPV-HepB-Hib', max_length=100, unique=True)),
                ('disease_targeted', models.CharField(max_length=200)),
                ('recommended_offset_days', models.IntegerField(help_text='Days from birth when this vaccine should be given (e.g., Birth = 0, 6 weeks = 42)')),
                ('dosage_number', models.IntegerField(default=1, help_text='Dose number in the series (e.g., 1, 2, 3)')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ADMINISTERED', 'Administered'), ('DELAYED', 'Delayed/Skipped')], default='PENDING', max_length=15)),
                ('scheduled_date', models.DateField(help_text='Calculated date: DOB + Vaccine Offset')),
                ('actual_administered_date', models.DateField(blank=True, help_text='The actual day the shot was given', null=True)),
                ('administered_by', models.CharField(blank=True, help_text='Doctor or Nurse name', max_length=150, null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Vaccine vial batch code for safety tracking', max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccinations.vaccinedefinition')),
            ],
            options={
                'ordering': ['scheduled_date'],
                'unique_together': {('patient', 'vaccine')},
            },
        ),
    ]
