# Generated by Django 5.2.15 on 2026-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('guardian_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('chronic_conditions', models.TextField(blank=True, help_text='E.g., Asthma, Type 1 Diabetes', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Food, drug, or environmental allergies', null=True)),
                ('is_preterm', models.BooleanField(default=False, help_text='Was the child born preterm?')),
                ('birth_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Birth weight in kilograms (e.g., 3.250)', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
