# Generated by Django 5.2.15 on 2026-06-18 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, help_text='Weight in kg (e.g., 12.450)', max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=2, help_text='Height/Length in cm (e.g., 85.50)', max_digits=5)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Head circumference in cm', max_digits=4, null=True)),
                ('clinical_notes', models.TextField(blank=True, help_text="Doctor's observations, symptoms, diagnosis", null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
